apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: 423671573423.dkr.ecr.us-east-1.amazonaws.com/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
